language: cpp
compiler: gcc
dist: bionic

if: branch = master OR branch = develop

git:
    quiet: true

before_install:
    - sudo apt update -qq > /dev/null

install: 
    - ./install_hdf5.sh

before_script:
    - mkdir build
    - cd build

script:
    - cmake ..
    - make
    - make test
