language: cpp
compiler: gcc
dist: bionic

if: branch = master OR branch = develop

git:
    quiet: true

before_install:
    - sudo apt update -qq > /dev/null

install: 
    - sudo apt install valgrind -qq > /dev/null
    - ./install_hdf5.sh

script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j `nproc --all`
    - make test
    - cd bin
    - for TEST in `ls`;
      do
          echo -e "\n\n$TEST\n----------------------------------------\n";
          valgrind --leak-check=yes --track-origins=yes --error-exitcode=1 ./$TEST;
      done
