language: cpp
compiler: gcc
dist: bionic

git:
    quiet: true

before_install:
    - sudo apt update -qq > /dev/null

install: 
    - sudo apt install gcc g++ make cmake -qq > /dev/null
    - sudo apt install libhdf5-serial-dev -qq > /dev/null

before_script:
    - mkdir build
    - cd build

script:
    - cmake ..
    - make
    - make test
