message("\n")
message("---- Project ${PROJECT_NAME} ----")
message("Version               = ${PROJECT_VERSION}")
message("Description           = ${PROJECT_DESCRIPTION}")
message("Homepage              = ${PROJECT_HOMEPAGE_URL}")
message("C++ compiler	      = ${CMAKE_CXX_COMPILER}")
message("Compiler flags	      = ${CMAKE_CXX_FLAGS}")
message("Compiler version      = ${CMAKE_CXX_COMPILER_VERSION}")
message("Coverage dependencies = ${CODE_COVERAGE_DEPENDENCIES}")
message("Catch2 version        = ${Catch2_VERSION}")
message("HDF5 version          = ${HDF5_VERSION}")
message("\n")
